### ISSUE TITLE
Bug when loading with quicklisp

### ISSUE THREAD

**Issue by Gfloresechaiz** [adlai/cjhunt#3]
whenever I try to (ql:quickload "cjhunt")

This happens 
> Error: Unexpected end of file on #<FLEXI-STREAMS:FLEXI-IO-STREAM #x3020048C120D>
> While executing: PEEK-CHAR, in process listener(1).

What would be solution? 
Thanks

**Comment by adlai** [comment]
> whenever I try to (ql:quickload "cjhunt")

Please specify additional context, since this does work on my existing installation.

**Comment by adlai** [comment]
@Gfloresechaiz Please do not interpret issue closure as disinvitation from using scalpl; rather, it is emphasis that this should be neither the first trading -- nor the first common lisp! --software that you drive.
